### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError : Input/output error

### ISSUE THREAD

**Issue by kkyan1995** [kujason/avod#104]
there is a error when i run trainer code , it troubled me many days , is there anyone meet the same problem? hope someone can help me. thank you!!

Traceback (most recent call last):
  File "avod/experiments/run_training.py", line 88, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "avod/experiments/run_training.py", line 84, in main
    train(model_config, train_config, dataset_config)
  File "avod/experiments/run_training.py", line 41, in train
    trainer.train(model, train_config)
  File "/mnt/data/yanjuan/avod-master/avod/core/trainer.py", line 123, in train
    sess.graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/summary/writer/writer.py", line 336, in __init__
    filename_suffix)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 367, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnknownError: /mnt/data/yanjuan/avod-master/avod/data/outputs/avod_cars_example/logs/train/2018-08-25 16:33:48.655024; Input/output error.

wait for your answer!

**Comment by kkyan1995** [comment]
isn't there anyone meet the same problem?If you have a solution to this problem ,please give me some advice! i am very appreciate to you...

**Comment by kkyan1995** [comment]
i have settled the question, for me ,it is the error in avod/avod/core/trainer.py which the variable named datetime_str  can not  combination to generate a file because it has the character which is not alphabet .
