### ISSUE TITLE
ValueError: Invalid data split: trainval, possible_splits: [] when run gen_mini_batches.py

### ISSUE THREAD

**Issue by Sakura1221** [kujason/avod#117]
I met a question during the process of Mini-batch Generation.
I just run gen_mini_batches.py like this.
sakura@sakura-Z170X-UD3:~/avod-master$  `python scripts/preprocessing/gen_mini_batches.py`
Then the following information is fed back.
Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
    main()
  File "scripts/preprocessing/gen_mini_batches.py", line 120, in main
    car_dataset_config_path)
  File "/home/sakura/avod-master/avod/builders/dataset_builder.py", line 154, in load_dataset_from_config
    use_defaults=False)
  File "/home/sakura/avod-master/avod/builders/dataset_builder.py", line 191, in build_kitti_dataset
    return KittiDataset(cfg_copy)
  File "/home/sakura/avod-master/avod/datasets/kitti/kitti_dataset.py", line 85, in __init__
    .format(self.data_split, possible_splits))
### **ValueError: Invalid data split: trainval, possible_splits: []**
 I have placed the dataset correctly and finished all the procedures as ReadMe adviced, but met this problem when I run gen_mini_batches.py. Who knows how to solve it?

**Comment by kujason** [comment]
It looks like your `~/Kitti/object` folder is missing the data split text files. What is the output when you run
`ls ~/Kitti/object` ? You should see something like
```
testing
training
val.txt
train.txt
trainval.txt
```

**Comment by sgs678** [comment]
I met the question during the process of Mini-batch Generation.

Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
    main()
  File "scripts/preprocessing/gen_mini_batches.py", line 188, in main
    num_ppl_children)
  File "scripts/preprocessing/gen_mini_batches.py", line 68, in split_work
    do_preprocessing(dataset, indices)
  File "scripts/preprocessing/gen_mini_batches.py", line 17, in do_preprocessing
    mini_batch_utils.preprocess_rpn_mini_batches(indices)
  File "/home/scw4750/087/avod/avod/core/mini_batch_utils.py", line 97, in preprocess_rpn_mini_batches
    mini_batch_preprocessor.preprocess(indices)
  File "/home/scw4750/087/avod/avod/core/mini_batch_preprocessor.py", line 238, in preprocess
    image_shape=image_shape)
  File "/home/scw4750/087/avod/avod/datasets/kitti/kitti_utils.py", line 255, in create_sliced_voxel_grid_2d
    create_leaf_layout=True)
  File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 102, in voxelize_2d
    unique_indices[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0
13 / 2: 13902 anchors,   1732 iou > 0.0, for   5 Car(s) for sample 000217
1 / 2: Sample already preprocessed
Mini batches generated
All Done (Parallel)

I also have  placed the dataset correctly , but met this problem when I run gen_mini_batches.py.  How can  I solve it?Thank you very much!

**Comment by sgs678** [comment]
@kujason   I have place this folder correctly,but I have met the error,can you ask me why?Thank you!

Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
    main()
  File "scripts/preprocessing/gen_mini_batches.py", line 188, in main
    num_ppl_children)
  File "scripts/preprocessing/gen_mini_batches.py", line 68, in split_work
    do_preprocessing(dataset, indices)
  File "scripts/preprocessing/gen_mini_batches.py", line 17, in do_preprocessing
    mini_batch_utils.preprocess_rpn_mini_batches(indices)
  File "/home/scw4750/087/avod/avod/core/mini_batch_utils.py", line 97, in preprocess_rpn_mini_batches
    mini_batch_preprocessor.preprocess(indices)
  File "/home/scw4750/087/avod/avod/core/mini_batch_preprocessor.py", line 238, in preprocess
    image_shape=image_shape)
  File "/home/scw4750/087/avod/avod/datasets/kitti/kitti_utils.py", line 255, in create_sliced_voxel_grid_2d
    create_leaf_layout=True)
  File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 99, in voxelize_2d
    discrete_pts_2d.shape[0] - unique_indices[-1]) 
IndexError: index -1 is out of bounds for axis 0 with size 0
