### ISSUE TITLE
Running  gen_mini_batches.py error

### ISSUE THREAD

**Issue by sgs678** [kujason/avod#125]
Traceback (most recent call last):
File "scripts/preprocessing/gen_mini_batches.py", line 199, in 
main()
File "scripts/preprocessing/gen_mini_batches.py", line 188, in main
num_ppl_children)
File "scripts/preprocessing/gen_mini_batches.py", line 68, in split_work
do_preprocessing(dataset, indices)
File "scripts/preprocessing/gen_mini_batches.py", line 17, in do_preprocessing
mini_batch_utils.preprocess_rpn_mini_batches(indices)
File "/home/scw4750/087/avod/avod/core/mini_batch_utils.py", line 97, in preprocess_rpn_mini_batches
mini_batch_preprocessor.preprocess(indices)
File "/home/scw4750/087/avod/avod/core/mini_batch_preprocessor.py", line 238, in preprocess
image_shape=image_shape)
File "/home/scw4750/087/avod/avod/datasets/kitti/kitti_utils.py", line 255, in create_sliced_voxel_grid_2d
create_leaf_layout=True)
File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 102, in voxelize_2d
unique_indices[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0
13 / 2: 13902 anchors, 1732 iou > 0.0, for 5 Car(s) for sample 000217
1 / 2: Sample already preprocessed
Mini batches generated
All Done (Parallel)

I  have placed the dataset correctly , but met this problem when I run gen_mini_batches.py. How can I solve it?Thank you very much!

**Comment by sgs678** [comment]
Running gen_mini_batches.py error:

IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by sgs678** [comment]
How can I change this?who can help me?

File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 99, in voxelize_2d
    discrete_pts_2d.shape[0] - unique_indices[-1])

**Comment by LiuCKind** [comment]
I also met this problem. Have you solved this problem yet?

**Comment by WUT-xiaoming** [comment]
me too

**Comment by kristingwang** [comment]
The same problem. Anybody solved it?

**Comment by kristingwang** [comment]
I solved this problem. I printed the point cloud variable and found it was empty, and I also found some files in the "/avod/data/mini_batches/iou_2d/kitti/train/lidar/Car[ 0.5]" weren't generated. So I checked the code and it told me one file in the "~/Kitti/object/training/velodyne" is broken. Therefore, I extracted the /velodyne again. The problem is solved. I think that might help you guys. Good luck!

**Comment by Priyashbhugra** [comment]
/avod/data/mini_batches/iou_2d/kitti/train/lidar/Car[ 0.5] 

Hii, I am not sure what exactly these .npy files in Car[0.5] store.
If you have any idea can you please let me know.

Thanks in advance.
