### ISSUE TITLE
ValueError: Invalid data split: trainval, possible_splits: ['train', 'val']

### ISSUE THREAD

**Issue by LiuCKind** [kujason/avod#137]
/home/liuchengkan/avod/venv/bin/python /home/liuchengkan/avod/scripts/preprocessing/gen_mini_batches.py
Traceback (most recent call last):
  File "/home/liuchengkan/avod/scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
    main()
  File "/home/liuchengkan/avod/scripts/preprocessing/gen_mini_batches.py", line 120, in main
    car_dataset_config_path)
  File "/home/liuchengkan/avod/avod/builders/dataset_builder.py", line 154, in load_dataset_from_config
    use_defaults=False)
  File "/home/liuchengkan/avod/avod/builders/dataset_builder.py", line 191, in build_kitti_dataset
    return KittiDataset(cfg_copy)
  File "/home/liuchengkan/avod/avod/datasets/kitti/kitti_dataset.py", line 85, in __init__
    .format(self.data_split, possible_splits))
ValueError: Invalid data split: trainval, possible_splits: ['train', 'val']

Process finished with exit code 1

This error occurred when I ran gen_mini_batches.py. What can I do for this? Could you give some advice?

**Comment by kujason** [comment]
It looks like you need to download the `trainval.txt` split file into your KITTI folder.
