### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:   device='GPU'

### ISSUE THREAD

**Issue by LiuCKind** [kujason/avod#140]
No checkpoints found
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/usr/local/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

     [[Node: MaxBytesInUse = MaxBytesInUse[]()]]
I met this error when I run run_training,py. What can I do to solve this problem?

**Comment by kujason** [comment]
https://github.com/kujason/avod/issues/70#issuecomment-397898342

**Comment by zxzhao514** [comment]
Probably because you only have one GPU, try config "GPU device = 0"
