### ISSUE TITLE
Problem when generating mini batches

### ISSUE THREAD

**Issue by timudk** [kujason/avod#144]
I am trying to generate the mini batches but I am running in this problem. Any suggestions?

```
Clustering labels 3712 / 3712
Finished reading labels, clustering data...

Clustering labels 3712 / 3712
Finished reading labels, clustering data...

Generating mini batches in /media/watouser/Seagate_Backup/object_detection_3d/avod/avod/data/mini_batches/iou_2d/kitti/train/lidar
1 / 7481 No Cars for sample 000000 (Ground Truth Filter)
Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
    main()
  File "scripts/preprocessing/gen_mini_batches.py", line 136, in main
    do_preprocessing(car_dataset, None)
  File "scripts/preprocessing/gen_mini_batches.py", line 17, in do_preprocessing
    mini_batch_utils.preprocess_rpn_mini_batches(indices)
  File "/media/watouser/Seagate_Backup/object_detection_3d/avod/avod/core/mini_batch_utils.py", line 97, in preprocess_rpn_mini_batches
    mini_batch_preprocessor.preprocess(indices)
  File "/media/watouser/Seagate_Backup/object_detection_3d/avod/avod/core/mini_batch_preprocessor.py", line 238, in preprocess
    image_shape=image_shape)
  File "/media/watouser/Seagate_Backup/object_detection_3d/avod/avod/datasets/kitti/kitti_utils.py", line 247, in create_sliced_voxel_grid_2d
    image_shape=image_shape)
  File "/media/watouser/Seagate_Backup/object_detection_3d/avod/avod/datasets/kitti/kitti_utils.py", line 157, in get_point_cloud
    im_size=im_size)
  File "/media/watouser/Seagate_Backup/object_detection_3d/avod/wavedata/wavedata/tools/obj_detection/obj_utils.py", line 237, in get_lidar_point_cloud
    x, y, z, i = calib_utils.read_lidar(velo_dir=velo_dir, img_idx=img_idx)
ValueError: not enough values to unpack (expected 4, got 0)
```

My folder structure looks like this:
```
`-- object
    |-- testing
    |   |-- calib
    |   `-- image_2
    `-- training
        |-- calib
        |-- image_2
        |-- label_2
        |-- planes
        `-- velodyne
```

**Comment by timudk** [comment]
I found the bug: My velodyne folder was broken, i.e., some files were missing.
