### ISSUE TITLE
求助运行run_training.py报错

### ISSUE THREAD

**Issue by sgs678** [kujason/avod#151]
Traceback (most recent call last):
  File "avod/experiments/run_training.py", line 88, in <module>
    tf.app.run()
  File "/home/deeplearning/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "avod/experiments/run_training.py", line 84, in main
    train(model_config, train_config, dataset_config)
  File "avod/experiments/run_training.py", line 41, in train
    trainer.train(model, train_config)
  File "/media/scw4750/disk/zz/avod/avod/core/trainer.py", line 34, in train
    0, trainable=False, name='global_step')
  File "/home/deeplearning/.local/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 259, in __init__
    constraint=constraint)
  File "/home/deeplearning/.local/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 347, in _init_from_args
    with ops.init_scope():
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/deeplearning/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5109, in init_scope
    with outer_context(), name_scope(scope), control_dependencies(
  File "/home/deeplearning/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5776, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/deeplearning/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3852, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: '' is not a valid scope name

**Comment by kujason** [comment]
Would need more details to help with this issue.
