### ISSUE TITLE
No checkpoint found when doing inference

### ISSUE THREAD

**Issue by sarimmehdi** [kujason/avod#165]
Hello. This is the error:

```
Traceback (most recent call last):
  File "C:/Users/sarim/PycharmProjects/thesis/DPC/avod/experiments/run_inference.py", line 133, in <module>
    tf.app.run()
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\sarim\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:/Users/sarim/PycharmProjects/thesis/DPC/avod/experiments/run_inference.py", line 129, in main
    args.ckpt_indices)
  File "C:/Users/sarim/PycharmProjects/thesis/DPC/avod/experiments/run_inference.py", line 70, in inference
    model_evaluator.run_latest_checkpoints()
  File "C:\Users\sarim\PycharmProjects\thesis\DPC\avod\core\evaluator.py", line 373, in run_latest_checkpoints
    checkpoint_to_restore = self._saver.last_checkpoints[ckpt_idx]
IndexError: list index out of range
No checkpoints found

Process finished with exit code 1
```
Please tell me what I am doing wrong? A similar issue was encountered before but remains unanswered: https://github.com/kujason/avod/issues/164

**Comment by kujason** [comment]
Please check that there are checkpoints in the checkpoints folder, and that the path is specified correctly in the `checkpoint` text file.
