### ISSUE TITLE
__init__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by shaunkheng97** [kujason/avod#178]
Hi, i have this issue where I cannot run the mini-batches generation and running inference. I am using Tensorflow-gpu == 2.2.0 as I tried to install Tensorflow-gpu==1.3.0 but there is no such version. I am not sure if this is an issue to my problem and I could not solve it. Does anyone has the same problem?

```
shaunkheng@shaunkheng-UX303LNB:~/avod$ python avod/experiments/run_inference.py --checkpoint_name='pyramid_cars_with_aug_example' --data_split='val' --ckpt_indices=120 --device='1'
Traceback (most recent call last):
  File "avod/experiments/run_inference.py", line 10, in <module>
    import tensorflow as tf
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/shaunkheng/anaconda3/lib/python3.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

**Comment by kujason** [comment]
The code is compatible up to tensorflow 1.8 (and possibly up to 1.15, but we have not verified this). Also see #61
