### ISSUE TITLE
ImportError: No module named 'wavedata.tools'

### ISSUE THREAD

**Issue by arxidinakbar** [kujason/avod#185]
@kujason 
Hi, Occur the same issue when runnning _minibatch genereation_ as mentioned in #80.

```
Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 6, in <module>
    from avod.builders.dataset_builder import DatasetBuilder
  File "/home/omnisky/aixiding/avod/avod/builders/dataset_builder.py", line 6, in <module>
    from avod.datasets.kitti.kitti_dataset import KittiDataset
  File "/home/omnisky/aixiding/avod/avod/datasets/kitti/kitti_dataset.py", line 10, in <module>
    from wavedata.tools.core import calib_utils
ImportError: No module named 'wavedata.tools'
```

And found I could import wavedata successfully, but failed to import 'tools'. So would there still code maintaining/update in future?

best luck

**Comment by kujason** [comment]
https://github.com/kujason/avod/issues/80#issuecomment-404755570
Try adding `wavedata` to your Python path:
`export PYTHONPATH=$PYTHONPATH:/home/username/avod/wavedata`
