### ISSUE TITLE
TypeError: build() got multiple values for argument 'layers_config'

### ISSUE THREAD

**Issue by RMobina** [kujason/avod#191]
Hi,
Thank you for sharing your source code. When I run the run_training.py I face the following error:
ssh://server@134.102.219.166:2299/home/data/miniconda3/envs/tensorflow150/bin/python3.6 -u /home/data/PycharmProjects/avod-master/run_training.py
/home/data/miniconda3/envs/tensorflow150/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/data/PycharmProjects/avod-master/run_training.py", line 98, in <module>
    tf.app.run()
  File "/home/data/miniconda3/envs/tensorflow150/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/data/PycharmProjects/avod-master/run_training.py", line 94, in main
    train(model_config, train_config, dataset_config)
  File "/home/data/PycharmProjects/avod-master/run_training.py", line 41, in train
    trainer.train(model, train_config)
  File "/mnt/homedata/PycharmProjects/avod-master/avod/core/trainer.py", line 60, in train
    prediction_dict = model.build()
  File "/mnt/homedata/PycharmProjects/avod-master/avod/core/models/avod_model.py", line 254, in build
    is_training=self._is_training)
TypeError: build() got multiple values for argument 'layers_config'

I would be grateful if help me how to solve it

**Comment by kujason** [comment]
Hi RMobina, which pipeline_config file did you use for run_training.py?

**Comment by RMobina** [comment]
Hi 

> Hi RMobina, which pipeline_config file did you use for run_training.py?

Hi Kujason, I tried different pipline_config (for example
 pyramid_cars_with_aug_example) which I have this error for all of them. I could train and inference the network before but right now I got this error
