### ISSUE TITLE
Wrong at Evaluator&Inference script

### ISSUE THREAD

**Issue by chrisjuniorli** [kujason/avod#30]
Hi, I successfully trained the avod to 120000 iterations, but when I ran the evaluator&inference script, they both stopped when processing sample 002908, and the wrong was like

libpng error: Read Error
Traceback (most recent call last):
  File "avod/experiments/run_evaluation.py", line 130, in <module>
    tf.app.run()
  File "/home/prp/anaconda2/envs/py35tf13/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "avod/experiments/run_evaluation.py", line 126, in main
    evaluate(model_config, eval_config, dataset_config)
  File "avod/experiments/run_evaluation.py", line 83, in evaluate
    model_evaluator.repeated_checkpoint_run()
  File "/home/prp/chrisli/myavod/avod/avod/core/evaluator.py", line 460, in repeated_checkpoint_run
    self.run_checkpoint_once(checkpoint_to_restore)
  File "/home/prp/chrisli/myavod/avod/avod/core/evaluator.py", line 199, in run_checkpoint_once
    feed_dict = self.model.create_feed_dict()
  File "/home/prp/chrisli/myavod/avod/avod/core/models/avod_model.py", line 655, in create_feed_dict
    feed_dict = self._rpn_model.create_feed_dict()
  File "/home/prp/chrisli/myavod/avod/avod/core/models/rpn_model.py", line 643, in create_feed_dict
    shuffle=False)
  File "/home/prp/chrisli/myavod/avod/avod/datasets/kitti/kitti_dataset.py", line 424, in next_batch
    samples_in_batch.extend(self.load_samples(np.arange(start, end)))
  File "/home/prp/chrisli/myavod/avod/avod/datasets/kitti/kitti_dataset.py", line 277, in load_samples
    rgb_image = cv_bgr_image[..., :: -1]
TypeError: 'NoneType' object is not subscriptable

The system is Ubuntu 16.04 with python3.5 and tensorflow1.3.0.

Thanks for your help.

**Comment by bensondou** [comment]
Check if that specific image is loaded successfully. You can insert a line to print the shape of cv_bgr_image.

**Comment by chrisjuniorli** [comment]
Hi again
I solved this problem by modifying some codes related to loading the images. The function cv2.imread() sometimes fail when processing .png image.
