### ISSUE TITLE
ValueError: could not convert string to float: "b'0.00'"

### ISSUE THREAD

**Issue by Yc174** [kujason/avod#5]
(py35) yanchao@yanchao:~/avod$ python scripts/preprocessing/gen_mini_batches.py
Clustering labels 1 / 3712Traceback (most recent call last):
  File "scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
    main()
  File "scripts/preprocessing/gen_mini_batches.py", line 120, in main
    car_dataset_config_path)
  File "/home/yanchao/MyProjects/avod/avod/builders/dataset_builder.py", line 154, in load_dataset_from_config
    use_defaults=False)
  File "/home/yanchao/MyProjects/avod/avod/builders/dataset_builder.py", line 191, in build_kitti_dataset
    return KittiDataset(cfg_copy)
  File "/home/yanchao/MyProjects/avod/avod/datasets/kitti/kitti_dataset.py", line 131, in __init__
    self.kitti_utils = KittiUtils(self)
  File "/home/yanchao/MyProjects/avod/avod/datasets/kitti/kitti_utils.py", line 59, in __init__
    self.label_cluster_utils.get_clusters()
  File "/home/yanchao/MyProjects/avod/avod/core/label_cluster_utils.py", line 194, in get_clusters
    img_idx)
  File "/home/yanchao/MyProjects/avod/wavedata/wavedata/tools/obj_detection/obj_utils.py", line 125, in read_labels
    obj.truncation = float(p[1])
ValueError: could not convert string to float: "b'0.00'"

**Comment by melfm** [comment]
What version of `numpy` are you using?

**Comment by HandsLing** [comment]
i meet the mistake too
my numpy's version was 1.12.1

**Comment by HandsLing** [comment]
i solved this problem by upgrading numpy by using:
pip install -U numpy

**Comment by Yc174** [comment]
Thank you very much! @HandsLing

**Comment by melfm** [comment]
Just to confirm again, you need `numpy>=1.12.0` as specified in `requirements.txt`.

**Comment by kujason** [comment]
Updated numpy version requirement to 1.13.0

**Comment by Bovey0809** [comment]
Probably numpy should be updated to >1.12.1
