### ISSUE TITLE
InvalidArgumentError: 'MaxBytesInUse' 

### ISSUE THREAD

**Issue by kmotillo** [kujason/avod#70]
I'm running the script on a msi GT73EVR 7RE Gtx 1070 8Gb
I got this error when I try to train 
python3 avod/experiments/run_training.py --pipeline_config=avod/configs/avod_cars_example.config  --device='0' --data_split='train'

/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:98: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2018-06-13 14:39:45.607652: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
No checkpoints found
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1332, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1392, in _extend_graph
    graph_def.SerializeToString(), status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]

....................................................................................
...................................................................................

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: MaxBytesInUse = MaxBytesInUse[]()]]

Please help....!!!

**Comment by kujason** [comment]
In your error message:
... with these attrs. **Registered devices: [CPU]**, Registered kernels: device='GPU'

This seems like the GPU is not being used, or you are not using the GPU version of tensorflow. Try the following:
```
pip uninstall tensorflow
pip install tensorflow-gpu
```
If you only have 1 GPU on your system, make sure to set `--device='0'` for both training and evaluation.

**Comment by kmotillo** [comment]
thanks for your reply, I uninstalled tensorflow and reinstalled tensorflow-gpu but now I got a different error:
victor@victor-GT73EVR-7RE:~/avod$ python3 avod/experiments/run_training.py --pipeline_config=avod/configs/avod_cars_example.config  --device='0' --data_split='train'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "avod/experiments/run_training.py", line 9, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

By the way I have CUDA 9.2 and cuDNN 7.5 NVIDIA DRIVER VERSION 396.26 I'm not sure if it is ok.

**Comment by salmanahmedshaikh** [comment]
I am getting a similar error message.
However I do not have a GPU on my system.
Can I only use CPU for the training and evaluation?

**Comment by tsbiosky** [comment]
I get the same error ,how did you resolve the issue ? reinstall tensorflow-gpu ? with the 1.3 or higher?

**Comment by kmotillo** [comment]
As Kujason said,

pip uninstall tensorflow
pip install tensorflow-gpu

f you only have 1 GPU on your system, 
make sure to set --device='0' for both training and evaluation.

If you have more than 1 GPU, you should look for the id of each one, and set in:
--device='id' for both training and evaluation.

This worked for me.

**Comment by langelesl** [comment]
@salmanahmedshaikh  I have the same problem as you. Have you run evaluation or inference successfully with just CPU? If so, could you please tell me where I need to modify? Thank you.

**Comment by salmanahmedshaikh** [comment]
> @salmanahmedshaikh I have the same problem as you. Have you run evaluation or inference successfully with just CPU? If so, could you please tell me where I need to modify? Thank you.

@langelesl No, you need a system with GPU. It can't be run with CPU only system.

**Comment by langelesl** [comment]
> > @salmanahmedshaikh I have the same problem as you. Have you run evaluation or inference successfully with just CPU? If so, could you please tell me where I need to modify? Thank you.
> 
> @langelesl No, you need a system with GPU. It can't be run with CPU only system.

Ok. Thank you for your reply.
