### ISSUE TITLE
ImportError: cannot import name 'kitti_dataset_pb2'

### ISSUE THREAD

**Issue by thudepwcp17** [kujason/avod#82]
Why this module is  missing?
@melfm @kujason @fmigneault @asharakeh 
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
D:\Software\Pycharm\PyCharm 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py:19: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  module = self._system_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "D:\Software\Pycharm\PyCharm 2018.1.1\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Software\Pycharm\PyCharm 2018.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Research/Code/avod-master/scripts/preprocessing/gen_mini_batches.py", line 6, in <module>
    from avod.builders.dataset_builder import DatasetBuilder
  File "D:\Software\Pycharm\PyCharm 2018.1.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Research\Code\avod-master\avod\builders\dataset_builder.py", line 7, in <module>
    from avod.protos import kitti_dataset_pb2
ImportError: cannot import name 'kitti_dataset_pb2'

**Comment by melfm** [comment]
Did you run the script 'sh avod/protos/run_protoc.sh' to compile the protos files?
