### ISSUE TITLE
Anyone can send me a pretrained model,please?

### ISSUE THREAD

**Issue by Gebixiaochen** [kujason/avod#84]
My computer is poor that I can\t run the training process,  I hope someone can send me a pretrained AVOD-FPN checkpoint so that I can run the inference on the KITTI dataset.Thanks very much!

**Comment by lucasjinreal** [comment]
@Gebixiaochen I have a pretrained model, if you want I can send you

**Comment by kargarisaac** [comment]
@jinfagang 
Is it possible to send to me a pre-trained model? 
kargarisaac@gmail.com

**Comment by WangGangUCAS** [comment]
wanggang_student@163.con,thanks

**Comment by maxwellfrom** [comment]
@jinfagang Could you please to me a pre-trained one? My email mfl123@mail.ustc.edu.cn Thank you!

**Comment by maxwellfrom** [comment]
Have you tried to use avod in ROS?

**Comment by SternSu** [comment]
@jinfagang Could you please send me a pretrained model? My email is sternsu@foxmail.com. Thank you very much!

**Comment by langelesl** [comment]
@jinfagang  I'd appreciate it if you could send me a pretrained model. lauian795@gmail.com

**Comment by sgs678** [comment]
@jinfagang Can you give me a pre-training model, thank you very much, my email address is 2841121072@qq.com

**Comment by sgs678** [comment]
@jinfagang Can you give me a pre-training model, thank you very much, my email address is 2845121072@qq.com

**Comment by sgs678** [comment]
@jinfagang Can you give me a pre-training model, thank you very much, my email address is 2841121072@qq.com

**Comment by sgs678** [comment]
@jinfagang Can you give me a pre-training model, thank you very much, my email address is 2845121072@qq.com

**Comment by YaduKini** [comment]
I have finished running the inference on Kitti 3d dataset. 
How do i send the pretrained model?
@sgs678 @langelesl @maxwellfrom

**Comment by lucasjinreal** [comment]
@langelesl @sgs678 @YaduKini @maxwellfrom  Sorry for late update, if you need pretrained model you can download from this [link](http://talk.strangeai.pro/topic/58/avod-car-pretrained-model%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5)

**Comment by YaduKini** [comment]
@jinfagang Thanks a ton!

**Comment by langelesl** [comment]
@YaduKini Please send to lauian795@gmail.com Thanks a lot. By the way, I'm using a old laptop that CUDA and GPU-support could not be realized. Is it possible to running the inference with CPU on KITTI dataset?

**Comment by sgs678** [comment]
@jinfagang Thank you for sharing, I am having a problem now and ask for your help.When I run gen_mini_batches.py:

Traceback (most recent call last):
File "scripts/preprocessing/gen_mini_batches.py", line 199, in <module>
main()
File "scripts/preprocessing/gen_mini_batches.py", line 161, in main
num_car_children)
File "scripts/preprocessing/gen_mini_batches.py", line 68, in split_work
do_preprocessing(dataset, indices)
File "scripts/preprocessing/gen_mini_batches.py", line 17, in do_preprocessing
mini_batch_utils.preprocess_rpn_mini_batches(indices)
File "/home/scw4750/087/avod/avod/core/mini_batch_utils.py", line 97, in preprocess_rpn_mini_batches
mini_batch_preprocessor.preprocess(indices)
File "/home/scw4750/087/avod/avod/core/mini_batch_preprocessor.py", line 238, in preprocess
image_shape=image_shape)
File "/home/scw4750/087/avod/avod/datasets/kitti/kitti_utils.py", line 255, in create_sliced_voxel_grid_2d
create_leaf_layout=True)
File "/home/scw4750/087/avod/wavedata/wavedata/tools/core/voxel_grid_2d.py", line 100, in voxelize_2d
unique_indices[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by lucasjinreal** [comment]
@sgs678  You can ask questions on a AI specific community: http://talk.strangeai.pro there are some separate topics for 3D object detection

**Comment by sgs678** [comment]
@jinfagang  I think you should have done this step. Do you know where this is going wrong?

**Comment by sainisanjay** [comment]
Dear @jinfagang, I am not able to download pre-trained model from above mentioned link. Do you have any alternative??? i tried many times and kept 4-5 hours in downloading but it does not progress

**Comment by sainisanjay** [comment]
@Gebixiaochen @kargarisaac @qq497841592 @maxwellfrom, Did anybody downloaded pre-trained model which is mentioned in above link(from @jinfagang ), Kindly share with me on Google Drive or Gamil(sanjay.1987saini@gmail.com). Because i tried a lot to download from link but i failed.

**Comment by RMobina** [comment]
@YaduKini can you please send the pretrained model to me. My email address is aiexpert2015@gmail.com. Thanks a lot

**Comment by RMobina** [comment]
@langelesl @sgs678 @maxwellfro @jinfagang I would be grateful if you send me the pre-trained model, thank you very much, my email address is aiexpert2015@gmail.com

**Comment by zouliang1014** [comment]
> @Gebixiaochen我有一个训练有素的模型，如果你想我可以给你发送

下载链接失效了，请问能发一份么，892806211@qq.com  ,万分感谢

**Comment by BojanAndonovski71** [comment]
hi. Is anybody has success using AVOD with ROS?

**Comment by 619862306** [comment]
@zouliang1014 , @astronaut71  @jinfagang  @YaduKini ,
I would appreciate if you can send me the pre-trained model.
My email address is : caoqi@hdu.edu.cn
Thx

**Comment by sinead-li** [comment]
@YaduKini can you please send the pretrained model to me. My email address is sineadli@126.com. Thanks a lot

**Comment by LiangzgJlu** [comment]
@jinfagang can you please send the pretrained model to me. My email address is 841351602@qq.cpm. Thanks you very much!

**Comment by LEO961124** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

can you please send the pretrained model to me. My email address is 18079486616@163.cpm. Thanks you very much!

**Comment by kiranb222** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

Can you please share the pretrained model to me . email Id is  kiranb222@gmail.com

**Comment by sjsjsjsj11** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

The link is not working. Can you please share the pretrained model to me? Thank you very much. Email address: harveyhou96@outlook.com

**Comment by akamob** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

Can you please share the pretrained model to me? My email address is: yinc3696@smail.nchu.edu.tw
Thank you very much!

**Comment by jianghy1998** [comment]
> Can you please share the model ? My emailis: 15504412429@163.com 
Many thanks!

**Comment by jianghy1998** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

Can you please share the model ? My email is: 15504412429@163.com
Many thanks!

**Comment by minhthai1995** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

Hi, can you share me the model, my email is minh.nguyen6@monash.edu

**Comment by snehahegdek** [comment]
> @Gebixiaochen I have a pretrained model, if you want I can send you

Hello, can u please share the model, my email: shegde979@gmail.com

**Comment by Jesser1855** [comment]
Dear all, I am facing the same issue. 
could you please send me the pre-trained Model ? 
my e-mail adress is : jesserbouzid1@gmail.com
Thank you in advance.

**Comment by marwenmoslah** [comment]
Dear all, I am facing the same issue.
could you please send me the pre-trained Model ?
my e-mail adress is : marwenmoslah2014@gmail.com
Thank you in advance.
